app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();


Route::group(['prefix'=>'usuarios', 'middleware'=>'auth', 'where'=>['id'=>'[0-9]+']], function() {
    Route::get('', ['as'=>'user.index', 'uses'=>'UserController@index']);

    Route::get('/criar', ['as'=>'user.create', 'uses'=>'UserController@create']);
    Route::post('/store', ['as'=>'user.store', 'uses'=>'UserController@store']);
    
    Route::get('/permissoes/{id}', ['as'=>'user.permissoes', 'uses'=>'UserController@permissoes']);
    Route::post('/permissoes/{id}', ['as'=>'user.permissoes_store', 'uses'=>'UserController@permissoes_store']);

    Route::post('/editar_funcionario', ['as'=>'user.edit_por_cpf', 'uses'=>'UserController@edit_por_cpf']);
    Route::get('/editar/{id}', ['as'=>'user.edit', 'uses'=>'UserController@edit']);
    Route::post('/update/{id}', ['as'=>'user.update', 'uses'=>'UserController@update']);
    
    Route::get('/editar_user/{id}', ['as'=>'user.edit_user', 'uses'=>'UserController@edit_user']);
    Route::post('/update_user/{id}', ['as'=>'user.update_user', 'uses'=>'UserController@update_user']);
    
    Route::get('/excluir/{id}', ['as'=>'user.destroy', 'uses'=>'UserController@destroy']);

});


//ADICIONADOS

Route::group(['prefix'=>'pacotes',  'where'=>['id'=>'[0-9]+']], function() {//'middleware'=>'auth',
    Route::get('/', ['as'=>'pacote.index', 'uses'=>'PacoteController@index']);
     
    Route::get('/cadastrar', ['as'=>'pacote.create', 'uses'=>'PacoteController@create']);
    Route::post('/cadastrar', ['as'=>'pacote.store', 'uses'=>'PacoteController@store']);
    
    Route::get('/editar/{id}', ['as'=>'pacote.edit', 'uses'=>'PacoteController@edit']);
    Route::post('/editar/{id}', ['as'=>'pacote.update', 'uses'=>'PacoteController@update']);
    
    Route::get('/excluir/{id}', ['as'=>'pacote.destroy', 'uses'=>'PacoteController@destroy']);
});

Route::group(['prefix'=>'logs',  'where'=>['id'=>'[0-9]+']], function() {
    
    Route::get('/Normais', ['as'=>'relatorio.get_logs_normais', 'uses'=>'RelatorioController@relatorio_get_logs_normais']);
    Route::post('/Normais', ['as'=>'relatorio.post_logs_normais', 'uses'=>'RelatorioController@relatorio_post_logs_normais']);
    
    Route::get('/Anormais', ['as'=>'relatorio.get_logs_anormais', 'uses'=>'RelatorioController@relatorio_get_logs_anormais']);
    Route::post('/Anormais', ['as'=>'relatorio.post_logs_anormais', 'uses'=>'RelatorioController@relatorio_post_logs_anormais']);
    
//    Route::get('/logs', ['as'=>'relatorio.get_logs', 'uses'=>'RelatorioController@relatorio_get_logs']);
    
});

Route::group(['prefix'=>'graficos',  'where'=>['id'=>'[0-9]+']], function() {
    //não é necessario utilizar essa rota
    Route::get('/relatorio1', ['as'=>'relatorio.index', 'uses'=>'RelatorioController@index']);
    
    Route::get('/resumo', ['as'=>'relatorio.get', 'uses'=>'RelatorioController@relatorio_get']);
    Route::post('/resumo', ['as'=>'relatorio.post', 'uses'=>'RelatorioController@relatorio_post']);
});

Route::group(['prefix'=>'arquitetura',  'where'=>['id'=>'[0-9]+']], function() {//'middleware'=>'auth',
    Route::get('/', ['as'=>'arquitetura.index', 'uses'=>'ArquiteturaController@index']);
     
    Route::get('/cadastrar_arquitetura', ['as'=>'arquitetura.create', 'uses'=>'ArquiteturaController@create']);
    Route::post('/cadastrar_arquitetura', ['as'=>'arquitetura.store_arquitetura', 'uses'=>'ArquiteturaController@store_arquitetura']);
    
    Route::post('/cadastrar_componente', ['as'=>'arquitetura.store_componente', 'uses'=>'ArquiteturaController@store_componente']);
    Route::post('/cadastrar_elemento', ['as'=>'arquitetura.store_elemento', 'uses'=>'ArquiteturaController@store_elemento']);
    
    Route::get('/importar', ['as'=>'arquitetura.importar_get', 'uses'=>'ArquiteturaController@importar_get']);
    Route::post('/importar', ['as'=>'arquitetura.importar_post', 'uses'=>'ArquiteturaController@importar_post']);
    
    Route::post('/importar_outro_diagrama', ['as'=>'arquitetura.importar_outro_diagrama_post', 'uses'=>'ArquiteturaController@importar_outro_diagrama_post']);
    
    Route::get('/componente/{id}', ['as'=>'arquitetura.show', 'uses'=>'ArquiteturaController@show']);
    
    Route::get('/editar/{id}', ['as'=>'arquitetura.edit', 'uses'=>'ArquiteturaController@edit']);
    Route::post('/editar/{id}', ['as'=>'arquitetura.update', 'uses'=>'ArquiteturaController@update']);
    
    Route::get('/excluir/{id}', ['as'=>'arquitetura.destroy', 'uses'=>'ArquiteturaController@destroy']);
});

Route::group(array('prefix' => 'api/v1'), function()
{   
    Route::resource('arquitetura', 'ArquiteturaController');//show
});

app/Http/Controllers/ArquiteturaController.php
<?php

namespace app\Http\Controllers;

use Illuminate\Http\Request;
use app\Entities\Arquitetura;
use Auth;
use DB;

class ArquiteturaController extends Controller
{
//string com endereço localhost: arquitetura_editar, arquitetura_show
    
    public function importar_get() {//por enquanto, trabalha apenas com 1 projeto por vez
        $user = Auth::user();
//        $this->authorize('is_admin', $user);
             
//        TESTE
//        $arquivo = file_get_contents('logs/abnormal.log');//.'.txt'
//        $arquivo = '['.str_replace("}\n{","},\n{",$arquivo).']';
//        $logs_json = json_decode($arquivo, true);
////        var_dump($logs_json);
//        
//        if (array_key_exists("exception",$logs_json[0])){
//            foreach ($logs_json as $log) {
//                $id = DB::table('anormal_logs')->insertGetId([
//                    'datetime' => $log['datetime'],
//                    'executable' => $log['executable'],
//                    'args' => json_encode($log['args']),
//                    'cpuTime' => $log['cpuTime'],
//                    'wallTime' => $log['wallTime'],
//                    'returnType' => $log['returnType'],
//                    'exception_name'=> $log['exception']['name'],
//                    'exception_file'=> $log['exception']['file'],
//                    'exception_line'=> $log['exception']['line'],
//                    'exception_message'=> $log['exception']['message'],
//                ]);
//            }
//        } else {
//            foreach ($logs_json as $log) {
//                $id = DB::table('normal_logs')->insertGetId([
//                    'datetime' => $log['datetime'],
//                    'executable' => $log['executable'],
//                    'args' => json_encode($log['args']),
//                    'cpuTime' => $log['cpuTime'],
//                    'wallTime' => $log['wallTime'],
//                    'returnType' => $log['returnType'],
//                    'result' => $log['result'],
//                ]);
//            }
//        }
        
//        $arquitetura = DB::select('select * from componentes where id_componente_pai = 0');//? AS 'pacote',
//        $elementos = DB::select("SELECT ? AS 'pacote', AVG(`cpuTime`) AS 'avg_cpuTime', AVG(`wallTime`) AS 'avg_wallTime' "
//                . "FROM `normal_logs` "
//                . "WHERE `executable` LIKE '?%'", ['br.com2', 'br.com2']);
        
        
//        $elementos = array();
//        $componentes = DB::select('select * from componentes where id_componente_pai = 0');//.$id);
//        foreach ($componentes as $componente){
//            $log = DB::select("SELECT  AVG(`cpuTime`) AS 'avg_cpuTime', AVG(`wallTime`) AS 'avg_wallTime' " 
//                                ."FROM `normal_logs` " 
//                                ."WHERE `executable` LIKE '".$componente->pacote_componente."%'");
//            
//            $ar_merge = array_merge( (array)$componente, (array)$log[0] );
//            array_push($elementos, $ar_merge);
//        }
//        dd($elementos);
        
        return view('arquitetura.arquitetura_importar');//, ['id'=>$id]
    }
    
    public function importar_post(Request $request){
        $user = Auth::user();
//        $this->authorize('is_admin', $user);
//        TODO TRATAR O ARQUIVO
        
//        $titulo = $request['titulo_logs'];
//        $titulo = 'log_1';

        if ($request->hasFile('logs')) {
//            $request->file('logs')->move(base_path() . 'logs/', $titulo.'.txt');//$nome_imagem
//            $arquivo = file_get_contents('logs/'.$titulo.'.txt');
            
//          Por enquanto, armazena temporariamente os logs para poder ser lido
//          Se não está escrevento o arquivo logs.txt, basta executar chmod 777 logs
            $request->file('logs')->move(base_path() . '/public/logs/', 'logs_temp.txt');//$nome_imagem
//            $arquivo = file_get_contents('logs/'.'abnormal.log');
//            $arquivo = file_get_contents('logs/'.'abnormal.txt');
            
//            $arquivo = file_get_contents('logs/'.'abnormal.log');//passar logs.txt para leitura
            
            $arquivo = file_get_contents('logs/'.'logs_temp.txt');
            $arquivo = '[' . str_replace("}\n{", "},\n{", $arquivo) . ']';
//            dd($arquivo);
            $logs_json = json_decode($arquivo, true);
//            dd($logs_json);
            
            if (array_key_exists("exception",$logs_json[0])){
                foreach ($logs_json as $log) {
                    $id = DB::table('anormal_logs')->insertGetId([
                        'datetime' => $log['datetime'],
                        'executable' => $log['executable'],
                        'args' => json_encode($log['args']),
                        'cpuTime' => $log['cpuTime'],
                        'wallTime' => $log['wallTime'],
                        'returnType' => $log['returnType'],
                        'exception_name'=> $log['exception']['name'],
                        'exception_file'=> $log['exception']['file'],
                        'exception_line'=> $log['exception']['line'],
                        'exception_message'=> $log['exception']['message'],
                    ]);
                }
                \Session::flash('success','Logs importados com sucesso!');
            } else {
    //            normal
                foreach ($logs_json as $log) {
                    $id = DB::table('normal_logs')->insertGetId([
                        'datetime' => $log['datetime'],
                        'executable' => $log['executable'],
                        'args' => json_encode($log['args']),
                        'cpuTime' => $log['cpuTime'],
                        'wallTime' => $log['wallTime'],
                        'returnType' => $log['returnType'],
                        'result' => $log['result'],
                    ]);
                }
                \Session::flash('success','Logs importados com sucesso!');
            }
        }
        return redirect()->back();
    }
    
    protected function importar_outro_diagrama_post(Request $request){
        $user = Auth::user();
//        $this->authorize('is_admin', $user);

        $file =  $request->file('diagrama');
        $nome_imagem = $file->getClientOriginalName();
        
//        $id = DB::table('outros_diagramas')->insertGetId([
//                    'id_componente_pai' => 0,
//                    'id_componente_irmao' => 0,
//                    'nome_imagem' => $nome_imagem,
////                    'pacote_componente' => '',//$request['pacote_componente'],
//                ]);
        
//        VER SE USO ISSO OU NÃO
        $id = DB::table('componentes')->insertGetId([
                    'titulo_grupo' => $request['titulo_diagrama'],
                    'id_componente_pai' => $request['id_componente_pai'],
                    'id_componente_irmao' => $request['id_componente_irmao'],
                    'nome_imagem' => $nome_imagem, 
                    'e_diagrama' => 1,
                ]);
        
        if ($request->hasFile('diagrama')) {
            $file->move(base_path() . '/public/imagens/', $nome_imagem);
        }
        
//        \Session::flash('success','Arquitetura principal salva!');
        return redirect()->route('arquitetura.index');
    }
    
    public function index() { //METODO PARA EXIBIR MAIS COMPLETO
        $user = Auth::user();
//        $this->authorize('is_admin', $user);
        
//         $arquiteturas = Arquitetura::paginate(20);//where('ativo', 1)->
//         return view('arquitetura.arquitetura_index', ['arquiteturas' => $arquiteturas]);
        
        $arquitetura = DB::select('select * from componentes where id_componente_pai = 0');
        
        
        if(count($arquitetura)>0){//mudar de ==1 para > 
            $diagramas_irmaos = DB::select('select * from componentes where id_componente_irmao = ?',[$arquitetura[0]->id_componente_irmao]);//
//            var_dump($diagramas_irmaos);
            $componentes = $this->contabiliza_metricas($arquitetura[0]->id);
//            dd($arquitetura);
            return view('arquitetura.arquitetura_index', ['componentes' => json_encode($componentes), 
                                                            'arquitetura'=>$arquitetura, 'diagramas_irmaos'=>json_encode($diagramas_irmaos)]);
        }
        return view('arquitetura.arquitetura_index', ['componentes' => json_encode([]), 'arquitetura'=>[], 'diagramas_irmaos'=>[]]);
    }
    
    public function show($id)
    {
        $user = Auth::user();
//        $this->authorize('is_admin', $user);
        
        $arquitetura = DB::select('select * from componentes where id = '.$id);
        $diagramas_irmaos = DB::select('select * from componentes where id_componente_irmao = ?',[$arquitetura[0]->id_componente_irmao]);//
//        dd($diagramas_irmaos);
        $componentes = $this->contabiliza_metricas($id);
        return view('arquitetura.arquitetura_show', ['componentes' => json_encode($componentes), 'arquitetura'=>$arquitetura, 
                                                        'diagramas_irmaos'=>json_encode($diagramas_irmaos)]);
    }
    
    
    
    protected function contabiliza_metricas($id_componente_pai){
        $componentes_vis_db = DB::select('select * from componentes where id_componente_pai = '.$id_componente_pai.' AND e_diagrama = 0');//
        $componentes = array();
        
        foreach ($componentes_vis_db as $componente){
           $normal_log = DB::select("SELECT  AVG(`cpuTime`) AS 'avg_cpuTime', AVG(`wallTime`) AS 'avg_wallTime' "
                                . "FROM `normal_logs` "
                                . "WHERE `executable` LIKE '" . $componente->pacote_componente . ".%'"
                                );
                
           $anormal_log = DB::select("SELECT  COUNT(*) AS 'qtd_exception' "

resources/views/arquitetura/arquitetura_create.blade.php
@extends('layouts.app')

@section('conteudo')
<div >
    
    <!-- 6. $HORIZONTAL_FORM ===========================================================================

                                Horizontal form
    -->
    <form action="{{ route('arquitetura.store') }}" method="POST" class="panel form-horizontal" enctype="multipart/form-data">
        <div class="panel-heading">
            <span class="panel-title">Arquitetura</span>
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group no-margin-hr">
                        <label class="control-label">Nome da figura</label>
                        <input type="nome" name="nome" class="form-control" required>
                    </div>
                </div><!-- col-sm-6 -->
            </div><!-- row -->

            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group no-margin-hr">
                        <label class="control-label">Imagens do problema</label>
                        </br>
                         <!--imagem-->
                         <!--<input type="hidden" name="MAX_FILE_SIZE" value="150000" />-->
                        <input type="file" name="arquitetura_principal">
                    </div>
                </div>
            </div>  
            
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group no-margin-hr  text-right">
                        <button class="btn btn-primary">Salvar</button>
                    </div>
                </div><!-- col-sm-6 -->
            </div><!-- row -->
            
            
        </div>
    </form>

</div>
@endsection

resources/views/arquitetura/arquitetura_importar.blade.php
@extends('layouts.app')


@section('conteudo')

<!--
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.1/angular.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
  -->

    <form action="{{ route('arquitetura.importar_post') }}" method="POST" class="panel form-horizontal" enctype="multipart/form-data">
        <div class="panel-heading">
            <span class="panel-title">Importar logs</span>
        </div>
        <div class="panel-body">
<!--            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group no-margin-hr" >
                        <label class="control-label">Título</label>
                        <input type="text" name="titulo_logs" class="form-control" required>
                    </div>
                </div>
            </div>-->
            
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group no-margin-hr" >
                        <label class="control-label">Arquivo</label>
                        <input type="file" name="logs" class="form-control"  required>
                    </div>
                </div>
            </div>
            
            <input type="hidden" name="id" value="0">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group no-margin-hr  text-right">
                        <button  class="btn btn-primary"> Importar</button>
                    </div>
                </div>
            </div>
       </div>     
    </form>

@endsection

resources/views/arquitetura/arquitetura_index.blade.php
@extends('layouts.app')
<!--TODO COLOCAR O ID COMO O "NOME DO PACOTE_ATRIBUTO MONITORADO" PARA USAR O JAVASCRIPT E JQUERY PARA ALTERA A COR DOS ELEMENTOS--> 
<!--TODO COLOCAR UMA ARVORE COM OS ELEMENTOS PARA FACILITAR A NAVEGAÇÃO ENTRE COMONENTES--> 
<!--slider é preciso ajustar escala  http://api.jqueryui.com/slider/-->


@section('conteudo')

<!--
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.1/angular.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
  -->


<script>
$(document).ready(function(){
    var metade_div_quad = 25;

    $("#main-wrapper").dblclick(function(event){//mousemove(function(event){//#div_pai
           $("[name='pos_x']").val(event.pageX ); 
           $("[name='pos_y']").val(event.pageY); 
    });
});
</script>


@if(count($arquitetura)>0)
<div id="div_pai" > 
    
    <?php
        echo '<b> '. $arquitetura[0]->titulo_grupo .' </b><br/><br/> ';
        echo '<div id="div_img_arquitetura"> <img id="img_arquitetura" style=" z-index:1; " src="/imagens/'. $arquitetura[0]->nome_imagem .'" /> </div> <br/><br/> ';
    ?>
    
    <!--ESSE TRECHO DEVE SER COLOCADO NO SHOW-->
    <div class="row">
        <div class="col-sm-12">
            
            <!--text-right-->
            <div class="form-group no-margin-hr ">
                @if($arquitetura[0]->id_componente_pai > 0)
                    <a href="{{ route('arquitetura.show',['id'=>$arquitetura[0]->id_componente_pai])}}" class="btn btn-primary" > Pai </a>
                @endif
                @foreach(json_decode($diagramas_irmaos) as $diagrama)
                    <a href="{{ route('arquitetura.show',['id'=>$diagrama->id])}}" class="btn btn-success" >{{$diagrama->titulo_grupo}} </a>
                @endforeach
            </div>
        </div>
    </div>
@else
    <form action="{{ route('arquitetura.store_arquitetura') }}" method="POST" class="panel form-horizontal" enctype="multipart/form-data">
        <div class="panel-heading">
            <span class="panel-title">Carregar diagrama principal</span>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group no-margin-hr" >
                        <label class="control-label">Título</label>
                        <input type="text" name="titulo_grupo" class="form-control"  ng-model="titulo_grupo" required>
                    </div>
                </div>
            </div>
            
<!--            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group no-margin-hr">
                        <label class="control-label">Pacote</label>
                        <input type="text" name="pacote_componente" ng-model="pacote_componente" class="form-control">
                    </div>
                </div>
            </div>-->
            
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group no-margin-hr">
                        <label class="control-label">Diagrama</label>
                        <input type="file" name="arquitetura_principal">
                    </div>
                </div>
            </div>
            
            <input type="hidden" name="id" value="0">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            
             <div class="row">
                <div class="col-sm-12">
                    <div class="form-group no-margin-hr  text-right">
                        <a id="bt_cancelar_outro_diagrama" onclick="" class="btn btn-default" >Cancelar</a>
                        <button class="btn btn-primary" >Salvar</button>
                        <!--ng-click="SendData()"-->
                    </div>
                </div><!-- col-sm-6 -->
            </div><!-- row -->

            
       </div>     
    </form>
@endif
    
<!--como esta integrado com php, deve ficar na página-->
<script>
    var app = angular.module('app', [], function($interpolateProvider) {
        $interpolateProvider.startSymbol('<%');
        $interpolateProvider.endSymbol('%>');
    });
    
    app.controller('appController', function ($scope, $http, $sce) {
        $scope.componentes = <?= $componentes ?>;
        
        $scope.compara_eficiencia = function (){
            $scope.componentes.sort(function(a, b){return a.avg_cpuTime - b.avg_cpuTime;});//pos_x
            var indicador = 0;
            
            for(i = 0; i < $scope.componentes.length; i++){
                indicador++;
                $scope.componentes[i].ind_eficiencia = indicador;
            };
        };
        $scope.compara_eficiencia();
        
        
        $scope.compara_confiabilidade = function (){
            $scope.componentes.sort(function(a, b){return a.qtd_exception - b.qtd_exception;});//pos_x
            var indicador = 0;
            
            for(i = 0; i < $scope.componentes.length; i++){
                indicador++;
                $scope.componentes[i].ind_confiabilidade = indicador;
            };
        };
        $scope.compara_confiabilidade();
        
//        multiplicar pela escala
        $scope.seta_cor = function(p1, p2, escala, valor){
            if (valor < p1*escala){         //abaixo do limite
                return "btn-success";
            } else if (valor > p2*escala) { //acima do limite
                return "btn-danger";
            } else {                 //dentro do limite
                return "btn-warning";
            }    
        };
        
        $scope.seta_cor = function(p1, p2, escala, valor){
            if (valor < p1*escala){         //abaixo do limite
                return "btn-success";
            } else if (valor > p2*escala) { //acima do limite
                return "btn-danger";
            } else {                 //dentro do limite
                return "btn-warning";
            }    
        };
        
        $scope.seta_cor_indicador = function(p1, p2, escala, valor){
            if (valor < p1*escala){         //abaixo do limite
                return "label-success";
            } else if (valor > p2*escala) { //acima do limite
                return "label-danger";
            } else {                 //dentro do limite
                return "label-warning";
            }    
        };
        
        $scope.desenha_elementos = function (componentes){
            var _html = "";
            var metade_div_quad = 20;
            var i; 
            var item;
            var valor = 5;
            
            for(i = 0; i < componentes.length; i++){
                item = componentes[i];
                
                _html +=  "<div class='text_box2' style='position: absolute;";
                _html += "left: "+(item.pos_x-metade_div_quad)+"px; ";
                _html += "top: " +(item.pos_y-metade_div_quad)+"px; z-index:10;' > ";
//              CONTEUDO


                if(item.nome_imagem != ""){
//                    _html += '<a href="http://localhost:8000/arquitetura/componente/'+item.id+'" >';
//                    _html += '<i class="btn-rounded btn-primary btn-xs fa fa-external-link"> </i></a>';
                    _html += '<a class="btn btn-xs btn-labeled btn-primary a_link" href="http://localhost:8000/arquitetura/componente/'+item.id+'" >';
                    _html += '<span class="btn-label icon fa fa-external-link a_link"> </span>';
                    _html += '</a>';
                } else{
                    _html += '<a class="btn btn-xs btn-labeled btn-default a_link">';
                    _html += '<span class="btn-label a_link"> </span>';
                    _html += '</a>';
                }
//                _html += '<a class="btn btn-xs btn-xs">';
//                _html += '<span class="btn-label icon fa fa-user"> </span>';
//                _html += '</a>';


//                TODO COLOCAR O ID COMO O "NOME DO PACOTE_ATRIBUTO MONITORADO" PARA USAR O JAVASCRIPT E JQUERY PARA ALTERA A COR DOS ELEMENTOS
//               replicar na tela show
                _html += '<a><i class="btn-rounded ';
                _html += $scope.seta_cor(item.desempenho_p1, item.desempenho_p2, item.desempenho_escala, item.avg_cpuTime); //para teste, colocar valor no lugar do artributo
                _html += ' btn-xs fa fa-bolt"> </i></a>';
                
                _html += '<a><i class="btn-rounded ';
                _html += $scope.seta_cor(item.confiabilidade_p1, item.confiabilidade_p2, item.confiabilidade_escala, item.qtd_exception);
                _html +=' btn-xs fa fa-check"> </i></a>';
                
                //IMPRESSAO DOS NUMEROS
//                _html += '<span class="label label-danger">21</span>';//TESTE

                _html += '<span class="label '+$scope.seta_cor_indicador(item.desempenho_p1, item.desempenho_p2, item.desempenho_escala, item.avg_cpuTime)+'"'
                _html += "style=\'position: absolute;";
                _html += "left: "+(-7)+"px; "; // -24, 20 top para ficar do lado
                _html += "top: " +(43)+"px;'>";
                _html += $scope.componentes[i].ind_eficiencia + '</span>';//DO LADO NÃO FICA BOM POIS PODE SER 1 OU 2 DIGITOS
                
                _html += '<span class="label '+$scope.seta_cor_indicador(item.confiabilidade_p1, item.confiabilidade_p2, item.confiabilidade_escala, item.qtd_exception)+'"'
                _html += "style=\'position: absolute;";
                _html += "left: "+(27)+"px; "; // -41, 20 top para ficar do lado
                _html += "top: " +(43)+"px;'>";
                _html += $scope.componentes[i].ind_confiabilidade + '</span>';//TESTE
//                
//                _html += '<span class="badge badge-danger"'
//                _html += "style=\'position: absolute;";
//                _html += "left: "+(-30)+"px; ";
//                _html += "top: " +(25)+"px;'>";
//                _html += '12</span>';//nao fica tão bom
                
//                _html += '<span class="label">55</span>';
//                _html += '<span class="label badge-danger">5</span>';
//                
//                
//                
//                
//                
//                _html += '<a><i class="btn-rounded btn-danger btn-xs fa fa-bolt"> </i></a>';
//                _html += '<a><i class="btn-rounded btn-success btn-xs fa fa-check"> </i></a>';
//                
// OUTROS ATRIBUTOS
//                _html += '<a><i class="btn-rounded btn-warning btn-xs fa fa-user"> </i></a>';
//                _html += '<a><i class="btn-rounded btn-success btn-xs fa fa-th-large"> </i></a>';
//                _html += '<a><i class="btn-rounded btn-warning btn-xs fa fa-wrench"> </i></a>';
//                _html += '<a><i class="btn-rounded btn-danger btn-xs fa fa-cogs"> </i></a>';

                _html += "</div>";
            }
            
//          Inseri os elementos na tela
            $scope.snippet = $sce.trustAsHtml(_html);
        };
        
        $scope.desenha_elementos($scope.componentes);
    });
</script>

@endsection